"""Negative controls for fixed-reference outlined PDF inspection, not OCR."""
import importlib.util,json,tempfile
from pathlib import Path
import unittest
from reportlab.pdfgen.canvas import Canvas
import pypdfium2 as pdfium
MODULE=Path(__file__).resolve().parents[1]/'print_raster.py'
class PrintedDocumentTests(unittest.TestCase):
    def setUp(self):
        self.tmp=tempfile.TemporaryDirectory();self.addCleanup(self.tmp.cleanup);self.root=Path(self.tmp.name)
        spec=importlib.util.spec_from_file_location('print_raster',MODULE)
        self.m=importlib.util.module_from_spec(spec);spec.loader.exec_module(self.m);self.good=self.make('good')
        with pdfium.PdfDocument(self.good) as doc:
            page=doc[0];bitmap=page.render(scale=3);expected=self.m.fingerprint(bitmap.to_pil());bitmap.close();page.close()
        self.book={'schema':1,'scale':3,'sourceRun':'independent-reportlab-unit-fixture','productCommit':'none','cases':{'test':[expected]}}
        self.m.REFERENCE=self.root/'reference.json';self.write_book()
    def write_book(self):self.m.REFERENCE.write_text(json.dumps(self.book))
    def make(self,name):
        path=self.root/(name+'.pdf');c=Canvas(str(path),pagesize=(595.32,841.92) if name!='wrong-paper' else (612,792))
        c.setFont('Helvetica',14);c.drawString(80,760,'Known reference page 1')
        if name!='missing':c.drawString(80,730,'Final line Hg 1234567890')
        if name=='extra':c.showPage();c.drawString(80,760,'Extra page')
        c.save();return path
    def inspect(self,path):return self.m.inspect_print_pdf(path,{'pages':[{'size_pt':[595.28,841.86]}]},self.root/'out','test')
    def test_fixed_reference_matches_independent_pdf(self):self.inspect(self.good)
    def test_missing_printed_line_fails(self):
        with self.assertRaises(ValueError):self.inspect(self.make('missing'))
    def test_unrequested_extra_page_fails(self):
        with self.assertRaises(ValueError):self.inspect(self.make('extra'))
    def test_letter_cannot_pass_requested_a4(self):
        with self.assertRaisesRegex(ValueError,'paper'):self.inspect(self.make('wrong-paper'))
    def test_baseline_tampering_fails(self):
        self.book['cases']['test'][0]['maskSha256']='0'*64;self.write_book()
        with self.assertRaisesRegex(ValueError,'fingerprint'):self.inspect(self.good)
    def test_no_autogenerated_baseline(self):
        self.m.REFERENCE.unlink()
        with self.assertRaisesRegex(ValueError,'reference'):self.inspect(self.good)
if __name__=='__main__':unittest.main()
